app:
  title: B4llz Dev Portal
  baseUrl: ${BASE_URL}
organization:
  name: B4llz Corp

backend:
  baseUrl: ${BASE_URL}
  listen:
    port: 3000
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: ${BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

techdocs:
  builder: 'external'
  generator:
    runIn: 'local'
  publisher:
    type: 'googleGcs'
    googleGcs:
      projectId: ${TECHDOCS_PROJECT_ID}
      bucketName: ${TECHDOCS_BUCKET_NAME}

auth:
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

permission:
  enabled: true

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow:
        - User
        - Group
        - Component
        - API
        - Location
        - Resource
        - System
        - Template
  locations: []
  providers:
    github:
      mycatalog:
        organization: beverts312
        catalogPath: /**/*.yml
        filters:
          branch: 'main'
          repository: 'catalog'
        schedule:
          frequency:
            minutes: 120
          timeout:
            minutes: 3
      me:
        organization: beverts312
        catalogPath: catalog-info.yml
        filters:
          branch: 'main'
          repository: '.*'
        schedule:
          frequency:
            minutes: 180
          timeout:
            minutes: 3